### PR TITLE
Version 0.9

### PR DESCRIPTION
**Pull request by def-**
for official release

### CODE REVIEW

**Comment by edg-l** [comment]
Maybe before release we should do:

- Update to 0.7.4
- Use 0.7.4 race features such as timer, checkpoints
- Use server-side command api

**Comment by def-** [comment]
Those sound like reasonable improvements and once they're in I'd release a new version.

But let's just release the current state as it is so that people who want it now can use it. The version number should make it clear that this is not finished yet.

**Comment by fokkonaut** [comment]
I am not a fan of the vanilla race timer, having time in the game timer is much nicer. We could think about the checkpoints, but they are not too bad right now too, i made them red and green colored aswell.
What we definitely need is the race flag for the times.
@Ryozuki we can only add 22 commands to the list, we could do it like on my server, where i only put the important ones (/cmdlist, /info, /credits, ...), or we could do pages (which i tried and isnt too nice).

I could add the time stuff for scoreboard properly and also the chat command stuff if you'd like. But I wont be home in the next 2-3 days, so either you wait or do it yourself.

**Comment by def-** [comment]
Initial test build working now: https://github.com/ddnet/ddnet-scripts/blob/master/ddnet7-release.sh

https://ddnet.tw/downloads/DDNet7-0.9-win32.zip
https://ddnet.tw/downloads/DDNet7-0.9-win64.zip
https://ddnet.tw/downloads/DDNet7-0.9-osx.dmg
https://ddnet.tw/downloads/DDNet7-0.9.tar.xz
https://ddnet.tw/downloads/DDNet7-0.9-linux_x86.tar.xz
https://ddnet.tw/downloads/DDNet7-0.9-linux_x86_64.tar.xz

**Comment by def-** [comment]
The win64/win32 servers are huge at 16 MB each, maybe we're linking in too much?

**Comment by def-** [comment]
Fixed by adding a strip command, working fine now:

https://ddnet.tw/downloads/DDNet7-Server-0.9-win32.zip
https://ddnet.tw/downloads/DDNet7-Server-0.9-win64.zip
https://ddnet.tw/downloads/DDNet7-Server-0.9-osx.dmg
https://ddnet.tw/downloads/DDNet7-Server-0.9.tar.xz
https://ddnet.tw/downloads/DDNet7-Server-0.9-linux_x86.tar.xz
https://ddnet.tw/downloads/DDNet7-Server-0.9-linux_x86_64.tar.xz

**Pull request merged**
